name: GSI - Erfan

on: [push]

env:
  ROM: Generic:RR8.0
  ROM_LINK: http://tdrive.manofuranium.workers.dev/RROS-Q-8.4.9-20200727-guacamole-Official.zip
  MIR: gof
  MIR2: bit
  TZ: America/Sao_Paulo
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Set up python
         uses: actions/setup-python@v2
         with:
           python-version: '3.8.2'

       - name: Initializing telegram bot
         env:
              TOKEN: ${{ secrets.TOKEN }}

         run: |
              sudo install telegram /usr/bin
              chmod +x init.sh
              . init.sh
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/JamieHoSzeYui/ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Execute Shell Script
         env:
              TOKEN: ${{ secrets.TOKEN }}
              
         run: |
               chmod +x build.sh
               . build.sh
               
       - name: Copy and rename A-Only build info
         run: cp ErfanGSIs/output/*Aonly*.txt Aonly.txt

       - name: Send build info to Telegram
         env:
              CHAT_ID: ${{ secrets.CHAT_ID }}
              TOKEN: ${{ secrets.TOKEN }}
              API_ID: ${{ secrets.API_ID }}
              API_HASH: ${{ secrets.API_HASH }}

         run: |
              python .github/workflows/robot.py
              telegram -M "$ROM build is done and is uploaded to your channel, enjoy !"
